const studentsData = [
    {
      name: "rahul",
      rollNumber: 1,
      address: {
        city: "Pune",
        zipcode: 411037,
      },
      trainings: ["JAVA", "HTML"],
      level: "Intermediate",
      email: "rahul21@gmail.com",
    },
    {
      name: "manish",
      rollNumber: 2,
      address: {
        city: "Pune",
        zipcode: 411037,
      },
      trainings: ["JAVA", "HTML"],
      level: "Basic",
      email: "manish21@gmail.com",
    },
    {
      name: "rohit",
      rollNumber: 3,
      address: {
        city: "Pune",
        zipcode: 411037,
      },
      trainings: ["HTML"],
      level: "Advance",
      email: "rohit77@gmail.com",
    },
    {
      name: "sandip",
      rollNumber: 4,
      address: {
        city: "Pune",
        zipcode: 411037,
      },
      trainings: ["HTML", "JAVASCRIPT"],
      level: "Intermediate",
      email: "sandip90@gmail.com",
    },
    {
      id: 5,
      name: "rishabh",
      rollNumber: 7,
      address: {
        city: "Pune",
        zipcode: 411037,
      },
      trainings: ["HTML", "PYTHON"],
      level: "Intermediate",
      email: "rishabh25@gmail.com",
    },
    {
      name: "rushikesh",
      rollNumber: 9,
      address: {
        city: "Pune",
        zipcode: 411037,
      },
      trainings: ["PYTHON"],
      level: "Advance",
      email: "rushikesh9@gmail.com",
    },
    {
      name: "akshay",
      rollNumber: 14,
      address: {
        city: "Pune",
        zipcode: 411037,
      },
      trainings: ["HTML", "REACT"],
      level: "Advance",
      email: "akshay15@gmail.com",
    },
    {
      name: "satyam",
      rollNumber: 22,
      address: {
        city: "Pune",
        zipcode: 411037,
      },
      trainings: ["JAVASCRIPT", "ANGULAR"],
      level: "Advance",
      email: "satyam01@gmail.com",
    },
    {
      name: "aniket",
      rollNumber: 44,
      address: {
        city: "Pune",
        zipcode: 411037,
      },
      trainings: ["HTML", "JAVASCRIPT", "REACT"],
      level: "Advance",
      email: "aniket04@gmail.com",
    },
    {
      name: "rohan",
      rollNumber: 35,
      address: {
        city: "Pune",
        zipcode: 411037,
      },
      trainings: ["HTML", "JAVASCRIPT", "ANGULAR"],
      level: "Basic",
      email: "rohan35@gmail.com",
    },
    {
      name: "ketan",
      id: 11,
      rollNumber: 30,
      address: {
        city: "Pune",
        zipcode: 411037,
      },
      trainings: ["HTML", "REACT", "PYTHON"],
      level: "Intermediate",
      email: "ketan5@gmail.com",
    },
    {
      name: "harshit",
      rollNumber: 31,
      address: {
        city: "Pune",
        zipcode: 411037,
      },
      trainings: ["HTML", "REACT", "PYTHON"],
      level: "Intermediate",
      email: "harshit5@gmail.com",
    },
    {
      name: "prachi",
      rollNumber: 20,
      address: {
        city: "Pune",
        zipcode: 411037,
      },
      trainings: ["HTML", "REACT", "PYTHON"],
      level: "Intermediate",
      email: "ketan5@gmail.com",
    },
    {
      name: "sagar",
      rollNumber: 23,
      address: {
        city: "Pune",
        zipcode: 411037,
      },
      trainings: ["HTML", "REACT", "PYTHON", "ANGULAR"],
      level: "Intermediate",
      email: "sagar77@gmail.com",
    },
    {
      name: "kunal",
      rollNumber: 24,
      address: {
        city: "Pune",
        zipcode: 411037,
      },
      trainings: ["REACT", "RUBY"],
      level: "Intermediate",
      email: "ketan5@gmail.com",
    },
    {
      name: "om",
      rollNumber: 25,
      address: {
        city: "Pune",
        zipcode: 411037,
      },
      trainings: ["HTML", "REACT", "PYTHON", "ML"],
      level: "Intermediate",
      email: "om12@gmail.com",
    },
    {
      name: "nikhil",
      rollNumber: 13,
      address: {
        city: "Pune",
        zipcode: 411037,
      },
      trainings: ["HTML", "REACT", "ML"],
      level: "Intermediate",
      email: "nikhil9@gmail.com",
    },
    {
      name: "tejas",
      rollNumber: 15,
      address: {
        city: "Pune",
        zipcode: 411037,
      },
      trainings: ["HTML", "REACT", "PYTHON", "ANGULAR"],
      level: "Intermediate",
      email: "tejas87@gmail.com",
    },
    {
      name: "tanmay",
      rollNumber: 12,
      address: {
        city: "Pune",
        zipcode: 411037,
      },
      trainings: ["REACT"],
      level: "Intermediate",
      email: "tan09@gmail.com",
    },
    {
      name: "sachin",
      rollNumber: 21,
      address: {
        city: "Pune",
        zipcode: 411037,
      },
      trainings: ["HTML", "REACT", "PYTHON"],
      level: "Intermediate",
      email: "ketan5@gmail.com",
    },
    {
      name: "virendra",
      rollNumber: 16,
      address: {
        city: "Pune",
        zipcode: 411037,
      },
      trainings: ["HTML", "REACT", "PYTHON"],
      level: "Intermediate",
      email: "viru7@gmail.com",
    },
    {
      name: "virat",
      rollNumber: 18,
      address: {
        city: "Pune",
        zipcode: 411037,
      },
      trainings: ["HTML", "REACT", "PYTHON", "ML", "AI"],
      level: "Intermediate",
      email: "virat18@gmail.com",
    },
    {
      name: "ravindra",
      rollNumber: 8,
      address: {
        city: "Pune",
        zipcode: 411037,
      },
      trainings: ["PYTHON"],
      level: "Intermediate",
      email: "ravi8@gmail.com",
    },
    {
      name: "abhay",
      rollNumber: 5,
      address: {
        city: "Pune",
        zipcode: 411037,
      },
      trainings: ["HTML", "REACT", "PYTHON"],
      level: "Intermediate",
      email: "ab@gmail.com",
    },
    {
      name: "ashish",
      rollNumber: 6,
      address: {
        city: "Pune",
        zipcode: 411037,
      },
      trainings: ["HTML", "REACT", "PYTHON"],
      level: "Intermediate",
      email: "ashish00@gmail.com",
    },
    {
      name: "vineet",
      rollNumber: 10,
      address: {
        city: "Pune",
        zipcode: 411037,
      },
      trainings: ["ML"],
      level: "Intermediate",
      email: "vineet12@gmail.com",
    },
  ];

module.exports = studentsData;